### ISSUE TITLE
not able to install the dependencies on windows cmd through pip3 install . ?

### ISSUE THREAD

**Issue by purnima110895** [MischaU8/spevktator#1] opened 2023-03-17 15:09 UTC
Getting error - (venv) F:\spevktator\spevktator>pip3 install .
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

Please help how to install the dependencies on windows ?
@MischaU8

**Comment by MischaU8** [comment] 2023-03-23 18:55
Looks like you are in the wrong directory, try `F:\spevktator\` in your case since there will be a `pyproject.toml` file there.

**Comment by purnima110895** [comment] 2023-05-29 10:02
Yup. 

But getting another error , how to get rid of this -

(tutorial-env) F:\tutorial-env\Scripts\spevktator>spevktator fetch data/new.db life
Scraping VK domain 'life'... https://m.vk.com/life
HTTP Exception for https://m.vk.com/life - [WinError 10054] An existing connection was forcibly closed by the remote host
Scraping VK domain 'life'... https://m.vk.com/life
HTTP Exception for https://m.vk.com/life - [WinError 10054] An existing connection was forcibly closed by the remote host

Please help . @MischaU8

**Comment by purnima110895** [comment] 2023-05-29 11:47
Also not getting data , please check if something needs to be changed in the implemented library, because we have data on the website -

(vk-data) F:\vk-data\Scripts\spevktator>spevktator fetch data/vk.db vkusnoitochka
Scraping VK domain 'vkusnoitochka'... https://m.vk.com/vkusnoitochka
2023-05-29 11:24:36.231756 posts_added=0 last_post_added=False earliest_post_date=None page: 1 / 5
Nothing added, done with vkusnoitochka

(vk-data) F:\vk-data\Scripts\spevktator>spevktator backfill -u 16-05-2023 data/vk.db life
Scraping max 5 pages of posts for life, starting at 0, until date 2023-05-16T00:00:00
Scraping VK domain 'life'... https://m.vk.com/life
2023-05-29 11:39:40.194880 posts_added=0 last_post_added=False earliest_post_date=None page: 1 / 5
Nothing added, done with life

(vk-data) F:\vk-data\Scripts\spevktator>spevktator fetch -l 10 data/vk.db life
Scraping VK domain 'life'... https://m.vk.com/life
2023-05-29 11:40:44.974572 posts_added=0 last_post_added=False earliest_post_date=None page: 1 / 10
Nothing added, done with life

@MischaU8

**Comment by purnima110895** [comment] 2023-05-30 13:20
Any suggestions , Please help on above isssues. 
@MischaU8

**Comment by MischaU8** [comment] 2024-03-19 10:15
Duplicate of #2

**Closed as completed by MischaU8** 2024-03-19 10:15 UTC
