### ISSUE TITLE
Urgent* Nothing added, done with -group name- Problem

### ISSUE THREAD

**Issue by mhaydan** [MischaU8/spevktator#3] opened 2023-12-09 16:48 UTC
Hello @MischaU8, I have been using spevktator for a while now. In June, there was an issue related to **"Nothing added, done with -group name-"** notification. However it was fixed, and worked well for some time. Now I am facing with the same problem again.

I tried to adjust the new data format from VK to the scraper.py however the problem still exists. I really need to use the tool to complete my research, so it would be a great help if you could take a look at it.

Looking forward your reply, thanks!
![Datascrape error](https://github.com/MischaU8/spevktator/assets/135733500/2ed4eaf6-e9b6-4598-9fa9-4cdf76149675)

**Comment by MischaU8** [comment] 2024-03-19 10:16
Duplicate of #2

**Closed as completed by MischaU8** 2024-03-19 10:16 UTC
